### PR TITLE
[Feature] DATA-4844: Sink both Key and Value 4.0.0

### PR DESCRIPTION
**Pull request by johnnycaol**
#### [JIRA] What Jira tickets does this PR Address?
https://jira.wishabi.com/browse/DATA-4844

#### [SUMMARY] What's this PR do?
- [x] - Customized S3 connector to enable sinking both key and value
- [x] - Add a config `s3.sink.key` to control if you want to sink the key or not
- [x] - Add test cases for primitive types and nested types
- [x] - Currently, it supports the following types
```
Schema.Type.INT8,
Schema.Type.INT16,
Schema.Type.INT32,
Schema.Type.INT64,
Schema.Type.FLOAT32,
Schema.Type.FLOAT64,
Schema.Type.BOOLEAN,
Schema.Type.STRING,
Schema.Type.STRUCT
```

#### [TEST CASES] How should this be tested?
- [x] - Run `mvn test` to make sure all test cases pass

#### [USAGE] How should this be used?
1. Run `mvn install` to generate the jar on local
2. Replace `/usr/share/java/kafka-connect-s3/kafka-connect-s3-4.0.0.jar` with `/usr/share/java/kafka-connect-s3/kafka-connect-s3-flipp-4.0.0.jar`

3. In s3 connector config file, add the following lines to sink both key and value:
```
connector.class=io.confluent.connect.s3.S3SinkKeyValueConnector
s3.sink.key=true
```

### CODE REVIEW

**Comment by bellemare** [comment]
@johnnycaol 
Is this basically just a simple port of your code from 3.3 to 4.0 ?

**Comment by johnnycaol** [comment]
@bellemare That's correct.

**Comment by bellemare** [comment]
If it's just a port, it builds and passes all the tests, then I say ship it!

**Review by bellemare — APPROVED** [review]

**Comment by OneCricketeer** [comment]
Note: You could also achieve this with a transform. 

https://github.com/jcustenborder/kafka-connect-transform-archive

**Review by jfb-flipp — APPROVED** [review]
approving ex post facto

**Pull request merged**
